<?php

namespace AppBundle\Repository;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.

 */
class BookingRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param \DateTime $date
     * @return integer
     * @throws \Doctrine\ORM\NonUniqueResultException
     */

    public function overbooking(\DateTime $date)
    {

       $query = $this->createQueryBuilder('b')
            ->select('COUNT(t)')
            ->where('b.visitDate = :visitDate')
            ->setParameter('visitDate', $date)
            ->innerJoin('b.tickets','t')
            ->getQuery();

        return $query->getSingleScalarResult();




    }
}
